## NumPy basic operations

In [1]:
import numpy as np

In [2]:
myList=[1,2,3]

In [3]:
myList


[1, 2, 3]

In [4]:
type(myList)

list

In [5]:
arr=np.array(myList)

In [6]:
arr

array([1, 2, 3])

In [8]:
list1=[1,'2']
x=np.array(list1)
x

array(['1', '2'], dtype='<U11')

In [9]:
myList=myList*2
myList

[1, 2, 3, 1, 2, 3]

In [10]:
arr=arr*2  # difference bw list and array
arr

array([2, 4, 6])

In [12]:
arr.ndim # dimension of array

1

In [15]:
arr2=np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
arr2.ndim

2

In [18]:
#list of array operations
list1=[1,2,3]
list2=[1,4,5]
arr3=np.array([list1,list2])
arr3

array([[1, 2, 3],
       [1, 4, 5]])

In [19]:
arr3.itemsize #memory space occupied

4

In [20]:
arr3.size #number of elements

6

In [21]:
arr.dtype

dtype('int32')

In [22]:
arr3.shape #no of datasets and no of columns

(2, 3)

In [24]:
len(arr3)# length of array

2

In [25]:
arr3.reshape(3,2) #change the dimension

array([[1, 2],
       [3, 1],
       [4, 5]])

In [26]:
np.transpose(arr3) #transpose of array

array([[1, 1],
       [2, 4],
       [3, 5]])

In [27]:
arr3.T # transpose of array

array([[1, 1],
       [2, 4],
       [3, 5]])

In [28]:
arr3[1,1] # accessing elements

4

In [29]:
arr3[0:,2]

array([3, 5])

In [31]:
array4=np.array([[1,2],[2,3],[4,5]])
array4[0:2,1]

array([2, 3])

In [34]:
array5=np.linspace(1,3,10)  #divide the space evenly over specified range
array5

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [38]:
array5.min() #min value


1.0

In [39]:
array5.max() #max value

3.0

In [40]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [41]:
array5.sum() #sum of all elements

20.0

In [48]:
arr=np.array([[1,2],[5,3]])
arr.sum(axis=0)

array([6, 5])

In [49]:
arr.sum(axis=1)

array([3, 8])

In [50]:
np.sqrt(arr) #square root of each elements

array([[1.        , 1.41421356],
       [2.23606798, 1.73205081]])

## stack array

In [51]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])