## Feature Scaling

In [1]:
#Normalization of data[scaling]

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
dataset= pd.read_excel(r'C:/Users/Shambhavi/Downloads/datasets/stark_data.xlsx')
dataset.head()

Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0

In [5]:
X=dataset.iloc[:,:-1].values
X[:,2]

array(['Male', 'Male', 'Female', 'Male', 'Male', 'Female'], dtype=object)

In [7]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN',strategy='mean',axis=0)
imputer.fit(X[:,1:2])
X[:,1:2]=imputer.transform(X[:,1:2])
X[:,1:2]

array([[52.0],
       [27.0],
       [21.0],
       [19.0],
       [28.6],
       [24.0]], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X=LabelEncoder()
#column_gender encoding
X[:,2]=labelencoder_X.fit_transform(X[:,2])
X[:,2]

array([1, 1, 0, 1, 1, 0], dtype=object)

In [9]:
#column name encoding
X[:,0]=labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([2, 3, 0, 1, 4, 5], dtype=object)

In [10]:
#one hot encoder creates a column for each value obtained
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
X

array([[ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])

In [14]:
#feature scaling
from sklearn.preprocessing import StandardScaler
standardscalerX=StandardScaler()
X=standardscalerX.fit_transform(X)

In [15]:
X

array([[-4.47213595e-01, -4.47213595e-01,  2.23606798e+00,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
         2.13434010e+00,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
         2.23606798e+00, -4.47213595e-01, -4.47213595e-01,
        -1.45937784e-01,  7.07106781e-01],
       [ 2.23606798e+00, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -6.93204476e-01, -1.41421356e+00],
       [-4.47213595e-01,  2.23606798e+00, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -8.75626707e-01,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01,  2.23606798e+00, -4.47213595e-01,
         3.24046977e-16,  7.07106781e-01],
       [-4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
        -4.47213595e-01, -4.47213595e-01,  2.23606798e+00,
        -4.19571130e-01, -1.41421356e+00]])